services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/trello_timetracker
      CORS_ORIGINS: '["http://91.220.69.232","http://localhost:8080"]'
      TRELLO_API_KEY: ${TRELLO_API_KEY}
      TRELLO_API_TOKEN: ${TRELLO_API_TOKEN}
    extra_hosts:
      - "host.docker.internal:host-gateway"
